### ISSUE TITLE
Customization and Sync

### ISSUE THREAD

**Issue by Hristov94** [polarbearjngl/MMM-FastNotes#2]
I am just a MM noob, with OCD, so I get extra points, right?

1) Can I make the title bigger, than the content?
2) Is there a way to increase the update interval? This module is by far the best for me, but this constant blinking is just not fun!

Thanks!

**Comment by Hristov94** [comment]
Scratch that first one, didn't see 
`nameTextStyle:`
and
` contentTextStyle:`

**Comment by Hristov94** [comment]
Yeah, scratch both of those questions:
`updateInterval:` in ms
`nameTextStyle:`
`contentTextStyle:`

**Comment by polarbearjngl** [comment]
> Yeah, scratch both of those questions: `updateInterval:` in ms `nameTextStyle:` `contentTextStyle:`

sorry for late response. Yeah, i am personally not the guru of MM and JavaScript. The way how this module is developed is not the best option to do it (i am about the approach for list items update). So the only option to avoid blinking is about increasing _updateInterval_
