### ISSUE TITLE
MagicMirror fails to load after setting up this module

### ISSUE THREAD

**Issue by devonian79** [polarbearjngl/MMM-FastNotes#3]
I went through everything step by step and MM won't load if I include MMM-FastNotes in the config.js file. Not sure if things have changed and I can't find where the problem is. Debug mode won't load up either.

npm install python-shell and npm install sqlite3 give this error:

npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: magicmirror@2.25.0
npm ERR! notsup Not compatible with your version of node/npm: magicmirror@2.25.0
npm ERR! notsup Required: {"node":">=18"}
npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v16.20.2"}

Thank you!

**Comment by devonian79** [comment]
Figured it out - I got everything updated. Just took some of them a very long time to wrap (I thought it had been crashing).

**Comment by cliff04** [comment]
Hey! I've got a different issue regarding the instalment of the module on the raspberry pi 4. Whenever I try executing "sudo python3 -m pip install -r requirements.txt" I'm met with an error saying: "This environment is managed externally, and if I do python3 into the terminal and then try executing sudo python3 -m pip install -r requirements.txt it gives me a syntax error. 

Please help.
